modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}"
issueTrackerURL="https://github.com/CoolerProYT/CobblemonTCG/issues"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile="${mod_id}.png" #optional
credits="${credits}" #optional
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)
[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "coolerconfig"
type="required"
versionRange = "[21.1.1,)"
ordering = "AFTER"
side = "BOTH"
# this is a Cobblemon addon: cards show Cobblemon's Pokemon models and Pokemon rewards give packs
[[dependencies.${mod_id}]]
modId = "cobblemon"
type="required"
versionRange = "[1.8.1,)"
ordering = "AFTER"
side = "BOTH"
