plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

sourceSets {
    gametest {
        compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.output + sourceSets.main.runtimeClasspath
    }
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            if (project.hasProperty('exportArt')) {
                systemProperty('cobblemontcg.exportArt', rootProject.file(project.property('exportArt')).absolutePath)
                programArguments.addAll('--quickPlaySingleplayer', 'wiki-renders')
            }
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
        gameTestServer {
            type = 'gameTestServer'
            sourceSet = sourceSets.gametest
            gameDirectory = project.file('run/gametest')
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.gametest
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    jarJar(implementation("com.coolerpromc.coolerconfig:coolerconfig-neoforge-${minecraft_version}:${cooler_config_version}"))

    compileOnly("com.cobblemon:neoforge:${cobblemon_version}") { transitive = false }
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}"
    runtimeOnly("com.cobblemon:neoforge:${cobblemon_version}") { transitive = false }
    runtimeOnly "thedarkcolour:kotlinforforge-neoforge:${kotlin_for_forge_version}"
}

publishMods {
    file.set(jar.archiveFile)
    type = STABLE
    modLoaders.add("neoforge")
    changelog = rootProject.file("changelog.md").text
    displayName = mod_id + "-" + project.version + "+" + minecraft_version + "-neoforge"

    curseforge {
        projectId = "1728366"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("cobblemon")
        client=true
        server=true
    }

    modrinth {
        projectId = "G49gRlMM"
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("cobblemon")
    }
}